version: "3.7"

services:
  build:
    image: klakegg/hugo:0.79.1
    volumes:
      - .:/src
  server:
    container_name: local-hugo
    image: klakegg/hugo:0.79.1
    command: server
    volumes:
      - .:/src
    ports:
      - "1313:1313"
