version: "3.7"

services:
  build:
    image: klakegg/hugo:0.82.0-ext-alpine
    volumes:
      - .:/src
  server:
    container_name: local-hugo
    image: klakegg/hugo:0.82.0-ext-alpine
    command: server
    volumes:
      - .:/src:cached
    ports:
      - "1313:1313"
