name: Hugo

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version: [0.82.0]
        image: ["ext-alpine"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          version: ${{ matrix.version }}
          image: ${{ matrix.image }}
